name: "huzhao's blog"
description: "胡钊的个人博客"

# avatar: https://github.com/learner-h-zh/Hu.github.io/blob/main/images/profile_picture.jpg
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 分类
    url: /tags
paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: 
  email: 
  facebook:
  github: pianfan
  rss: # just type anything here for a working RSS icon
  twitter: 
  youtube:

footer-text: Copyright (c) 2024 Pianfan

url: https://learner-h-zh.github.io



